version: '3'

networks:
  kafka_cluster:
    driver: bridge

services:
  zookeeper:
    #image: ashokkumarchoppadandi/apache-kafka-zookeeper:0.0.1
    build:
      context: ./Zookeeper
    networks:
      - kafka_cluster
    ports:
      - "2181:2181" 
    hostname: zookeeper
    environment:
      HOSTNAME: zookeeper
      ZOOKEEPER_HOST: zookeeper
      ZOOKEEPER_PORT: 2181
  broker:
    #image: ashokkumarchoppadandi/apache-kafka-broker:0.0.1
    build:
      context: ./KafkaBrokerNode
    networks:
      - kafka_cluster
    depends_on:
      - zookeeper
    hostname: broker
    environment:
      HOSTNAME: broker
      BROKER_ID: 0
      LISTENER_TYPE: PLAINTEXT
      BROKER_HOST: broker
      BROKER_PORT: 9092
      DEFAULT_PARTITIONS: 3
      ZOOKEEPERS_LIST: 'zookeeper:2181'
    ports:
      - "9092:9092"
  connect:
    #image: ashokkumarchoppadandi/apache-kafka-connect:0.0.1
    build:
      context: ./KafkaConnectNode
    networks:
      - kafka_cluster
    depends_on:
      - zookeeper
      - broker
    hostname: connect
    environment:
      LISTENER_TYPE: PLAINTEXT
      BROKERS_LIST: 'broker:9092'
      CONNECT_HOST: connect
      CONNECT_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST: connect
      CONNECT_REST_ADVERTISED_PORT: 8083
    ports:
      - "8083:8083"
  postgres:
    image: postgres:11
    networks:
      - kafka_cluster
    depends_on:
      - zookeeper
      - broker
      - connect
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
