CONTAINER_NAME=$1
NAMENODE_CONTAINER=$2
SECONDARY_NAMENODE_CONTAINER=$3
RESOURCE_MANAGER_CONTAINER=$4
docker run -idt --name $CONTAINER_NAME --hostname $CONTAINER_NAME -e HOSTNAME=$CONTAINER_NAME -e NAMENODE_HOST=$NAMENODE_CONTAINER -e SECONDARY_NAMENODE_HOST=$SECONDARY_NAMENODE_CONTAINER -e RESOURCE_MANAGER_HOST=$RESOURCE_MANAGER_CONTAINER --link $NAMENODE_CONTAINER --link $SECONDARY_NAMENODE_CONTAINER --link $RESOURCE_MANAGER_CONTAINER ashokkumarchoppadandi/hadoop-spark-slavenode:latest
