#!/bin/sh
#set -e

PROPERTIES_FILE=$CONFLUENT_HOME/config/ksql-server.properties
sed -i -e "s/KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE/$KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE/" $PROPERTIES_FILE
sed -i -e "s/KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE/$KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE/" $PROPERTIES_FILE
sed -i -e "s/KSQL_LOGGING_PROCESSING_ROWS_INCLUDE/$KSQL_LOGGING_PROCESSING_ROWS_INCLUDE/" $PROPERTIES_FILE
sed -i -e "s/BOOTSTRAP_SERVERS/$BOOTSTRAP_SERVERS/" $PROPERTIES_FILE
sed -i -e "s/SCHEMAREGISTRY_URL/$SCHEMAREGISTRY_URL/" $PROPERTIES_FILE
sed -i -e "s/UI_ENABLED/$UI_ENABLED/" $PROPERTIES_FILE
sed -i -e "s/KSQL_STREAMS_AUTO_OFFSET_RESET/$KSQL_STREAMS_AUTO_OFFSET_RESET/" $PROPERTIES_FILE
sed -i -e "s/KSQL_STREAMS_COMMIT_INTERVAL_MS/$KSQL_STREAMS_COMMIT_INTERVAL_MS/" $PROPERTIES_FILE
sed -i -e "s/MAX_BYTES_BUFFERING/$MAX_BYTES_BUFFERING/" $PROPERTIES_FILE
sed -i -e "s/DESERIALIZATION_ERROR/$DESERIALIZATION_ERROR/" $PROPERTIES_FILE
sed -i -e "s/KSQL_STREAMS_NUM_STREAM_THREADS/$KSQL_STREAMS_NUM_STREAM_THREADS/" $PROPERTIES_FILE
sed -i -e "s/KSQL_SERVICE_ID/$KSQL_SERVICE_ID/" $PROPERTIES_FILE
sed -i -e "s/KSQL_SINK_PARTITIONS/$KSQL_SINK_PARTITIONS/" $PROPERTIES_FILE
sed -i -e "s/KSQL_SINK_REPLICAS/$KSQL_SINK_REPLICAS/" $PROPERTIES_FILE


cat $CONFLUENT_HOME/config/ksql-server.properties
echo "Starting KSQL Server on $HOSTNAME"
ksql-server-start $PROPERTIES_FILE
