MR_HISTORYSERVER_CONTAINER=$1
NAMENODE_CONTAINER=$2
RESOURCE_MANAGER_CONTAINER=$3
docker run -idt --name $MR_HISTORYSERVER_CONTAINER --hostname $MR_HISTORYSERVER_CONTAINER -e HOSTNAME=$MR_HISTORYSERVER_CONTAINER -e RESOURCE_MANAGER_HOST=$RESOURCE_MANAGER_CONTAINER -e NAMENODE_HOST=$NAMENODE_CONTAINER -p 19888:19888 --link $NAMENODE_CONTAINER --link $RESOURCE_MANAGER_CONTAINER ashokkumarchoppadandi/hadoop-mr-historyserver:latest
