NAMENODE_CONTAINER=$1
RESOURCE_MANAGER_CONTAINER=$2
docker run -idt --name $NAMENODE_CONTAINER --hostname $NAMENODE_CONTAINER -e HOSTNAME=$NAMENODE_CONTAINER -e NAMENODE_HOST=$NAMENODE_CONTAINER -e RESOURCE_MANAGER_HOST=$RESOURCE_MANAGER_CONTAINER  -p 50070:50070 ashokkumarchoppadandi/hadoop-namenode:latest
