#!/bin/sh
#set -e

PROPERTIES_FILE=$CONFLUENT_HOME/config/zookeeper.properties
sed -i -e "s/ZOOKEEPER_HOST/$ZOOKEEPER_HOST/" $PROPERTIES_FILE
sed -i -e "s/ZOOKEEPER_CLIENT_PORT/$ZOOKEEPER_CLIENT_PORT/" $PROPERTIES_FILE
sed -i -e "s/ZOOKEEPER_DATA_DIR/$ZOOKEEPER_DATA_DIR/" $PROPERTIES_FILE
sed -i -e "s/ZOOKEEPER_TICK_TIME/$ZOOKEEPER_TICK_TIME/" $PROPERTIES_FILE

echo "Starting Zookeeper on $ZOOKEEPER_HOST:$ZOOKEEPER_PORT"
zookeeper-server-start $PROPERTIES_FILE 
