RESOURCE_MANAGER_HOST=$1
NAMENODE_CONTAINER=$2
docker run -idt --name $RESOURCE_MANAGER_HOST --hostname $RESOURCE_MANAGER_HOST -e HOSTNAME=$RESOURCE_MANAGER_HOST -e RESOURCE_MANAGER_HOST=$RESOURCE_MANAGER_HOST -e NAMENODE_HOST=$NAMENODE_CONTAINER -p 8088:8088 --link $NAMENODE_CONTAINER ashokkumarchoppadandi/hadoop-resourcemanager:latest
