CONTAINER_NAME=$1
NAMENODE_CONTAINER=$2
RESOURCE_MANAGER_CONTAINER=$3
docker run -idt --name $CONTAINER_NAME --hostname $CONTAINER_NAME -e HOSTNAME=$CONTAINER_NAME -e NAMENODE_HOST=$NAMENODE_CONTAINER -e RESOURCE_MANAGER_HOST=$RESOURCE_MANAGER_CONTAINER --link $NAMENODE_CONTAINER ashokkumarchoppadandi/hadoop-secondarynamenode:latest
