version: '3'

networks:
  kafka_single_node_cluster:
    driver: bridge

services:
  kafka:
    image: ashokkumarchoppadandi/apache-kafka:0.0.1
    networks: 
      - kafka_single_node_cluster
    ports:
      - "2181:2181"
      - "9092:9092"
      - "8083:8083"
    hostname: myhost
    entrypoint: "./docker-entrypoint-compose.sh"
    environment:
      HOSTNAME: myhost
      ZOOKEEPER_HOST: myhost
      ZOOKEEPER_PORT: 2181
      BROKER_HOST: myhost
      BROKER_PORT: 9092
      BROKER_ID: 0
      DEFAULT_PARTITIONS: 3
      ZOOKEEPERS_LIST: myhost:2181
      DEFAULT_CONNECT_PORT: 8083
      BROKERS_LIST: myhost:9092
      CONNECT_HOST: myhost
      CONNECT_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST: myhost
      CONNECT_REST_ADVERTISED_PORT: 8083

